### ISSUE TITLE
Some items with Metadata not working as modifer

### ISSUE THREAD

**Issue by Wolfofthenyght** [UnderMybrella/TiM#1]
I've tried various items from various mods to add a variety of modifiers, and it seems that SOME items with metadata are not working correctly to add modifiers.
I have tested the following:
{
            "class":"tconstruct.modifiers.tools.ModRedstone",
            "arg0":0,
            "arg1":[
                {
                    "item":"RedstoneArsenal:material",
                    "damage":0
                }
            ],
            "arg2":[
                4
            ]
        },
        {
            "class":"tconstruct.modifiers.tools.ModAttack",
            "arg0":1,
            "arg1":[
                {
                    "appliedenergistics2:item.ItemMultiMaterial"
                }
            ],
            "arg2":[
                1
            ]
        },
        {
            "class":"tconstruct.modifiers.tools.ModAttack",
            "arg0":2,
            "arg1":[
                {
                    "appliedenergistics2:item.ItemMultiMaterial",
                    "damage":1
                }
            ],
            "arg2":[
                1
            ]
        },
        {
            "class":"tconstruct.modifiers.tools.ModToolRepair",
            "arg0":3,
            "arg1":[
                {
                    "item":"arsmagica2:Aum"
                }
            ],
            "arg2":[
                1
            ]
        },
        {
            "class":"tconstruct.modifiers.tools.ModExtraModifier",
            "arg0":4,
            "arg1":[
                {
                    "item":"ThaumicTinkerer:kamiResource"
                }
            ],
            "arg2":[
                1
            ]
        },
        {
            "class":"tconstruct.modifiers.tools.ModToolRepair",
            "arg0":5,
            "arg1":[
                {
                    "item":"witchery:witchsapling",
                                        "damage":1
                }
            ],
            "arg2":[
                2
            ]
        }
Out of this, the only one that worked was the Certus Quartz from AE2. I have also tried adding "damage":meta to specify the meta data, but that doesn't seem to work either.

**Comment by UnderMybrella** [comment]
Okay, I can't do a lot of testing, but I can offer a bit of help with the config:
Problem #1 - You occasionally miss the "item" tag in front of the item name
Problem #2 - Comments don't work on lines unfortunately, so //This is whatever doesn't work
Problem #3 - Wrong arguments. Most of those modifiers don't take the same set of parameters, meaning that they're not going to be added. Certus Quartz is normally added by Tinkers' as an attack modifier. 
Sort of Problem #4 - Auto repair is actually not under ModToolRepair, that's the materials fixing the tool. I'm probably going to add in a separate AutoRepair since it falls under a specific ModInteger key unfortunately

**Comment by Wolfofthenyght** [comment]
Ookie dokie. I'll fix number one that you pointed out :) As for number 2, I just added those in for this post, don't worry, they're not in the actual config xD And that sounds good! Thank you for the info, I'll see if I can fix number 3 by referring to the text files it's creating for the modifiers :3
