### ISSUE TITLE
help with ModCustomAttack

### ISSUE THREAD

**Issue by stacra** [UnderMybrella/TiM#2]
So I've been playing around with this modifier for quite a while now. The reinforced seems to work fine but for attack mod I keep getting "java.lang.IllegalStateException: This is not a JSON Array.". I tried other constructors too but they ended up the same. I also get that error when trying to add luck mod. Any ideas what am I missing?

```
{
    "clear":[],
    "addModifiers":[
        {
            "class":"org.abimon.mods.minecraft.tmodifiers.modifiers.ModCustomAttack",
            "params":[
                [
                        {
                            "item":"OreSpawn:OreSpawn_Amethyst"
                        }
                ],
                11,
                "1254",
                4,
                2,
                "§4",
                "Crystalization2",
                [
                    {
                        "entity":"ANY_CREATURE"
                    }
                ],
                10,
                false
            ]
        },
        {
            "class":"org.abimon.mods.minecraft.tmodifiers.modifiers.ModCustomReinforced",
            "params":[
                [
                    {
                        "item":"OreSpawn:OreSpawn_Ruby"
                    }
                ],
                16,
                "Crystalized2",
                2,
                "§4",
                "Crystalization",
                6,
                1
            ]
        }
    ]
}
```

Also what am I supposed to write in ENTITY_LIST field? (I just goggled around and wrote whatever I could get...)
Thanks

**Comment by UnderMybrella** [comment]
Two things,
First off, apologies about the ENTITY_LIST field, that's actually the source of the error; that's just an array of strings the attack boost affects, with each string matching the class of the entity affected. To affect all entities, an asterisk should be sufficient ("*").
Second, there might be another error with the modifier and applying it, if so I'm aware of it and it should be fixed in an update soon.

**Comment by stacra** [comment]
Thanks for the long waited reply :)
So yeah doing [ "*" ] works but the actual damage doesn't change on weapons no matter how much modifier i apply.
Well then i guess I'll be waiting for the update (hope to get it soon).

**Comment by UnderMybrella** [comment]
When you say the actual damage doesn't change, do you mean the number at the bottom ("+ 8 damage") or the actual damage it deals?

**Comment by stacra** [comment]
Both, I can see the modifier applied but damage number doesnt change and it deals the same damage as unmodified.

**Comment by UnderMybrella** [comment]
That's really weird, I'll double check everything when I get home, and then I'll get back to you

**Comment by UnderMybrella** [comment]
Okay, might have figured out the problem - the last parameter in your ModCustomAttack is false, which is whether it functions as a whitelist or not. Since you have that set to false, it's functioning as a blacklist, and with '*' that's blacklisting all entities. Change the last parameter to true, and then see if that works

**Comment by stacra** [comment]
I changed it to true and also tried removing it completely - it doesnt make any difference, it still shows the same and deals the same amount of damage.

**Comment by stacra** [comment]
Ok... So I dug into minecraft files, and insted of "*" i wrote "monster". The tooltip still doesnt change, but after applying 2 stacks of modifier (20 amethysts), the actual damage dealt increased by somewhere 7 (the damage varies). And as you said, if i type true, it affects only monsters, if false or if I delete it at all, it affects everything except monsters. Yeah,  you should check that asterisk of yours, you might have made an typo somewhere :D
EDIT: Actually, just empty " ", without asterisk, is enough to pick all mobs.

**Comment by UnderMybrella** [comment]
Damn, I'm a genius. You're mostly right, there's a slight typo - I'm not directly matching against '*', I'm trying to match against regex, and by itself an asterisk isn't part of regex. That'll be fixed next version, sorry about the problems

**Comment by stacra** [comment]
Well then, the only thing left is tooltip not changing - and we will be done about this problem.

**Comment by UnderMybrella** [comment]
Changed the tooltip, each attack modifier should now tell you how much additional damage the modifier does. Nothing about what entities it affects, but there's not enough space for that.

Fix will be in the next update, so expect to see it soonish.

**Comment by stacra** [comment]
Thanks for helping, and best of luck in the future :+1:
