### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Claycorp** [UnderMybrella/TiM#3]
When loading the game there's a few hundred lines of console spam.
Here is a small snip of it: http://pastebin.com/fhWCpAfP

Also whenever someone hits an entity it prints a line with the damage done and some other junk.

This should be pruned or be made optional as its quite worthless and most people don't even need this information.

**Comment by UnderMybrella** [comment]
Okay, odd, I thought I'd removed that before release...
Anyway, I've gone through and pruned as much as I could find, so this should be resolved in the next release (Hopefully tonight)
Sorry about that

**Comment by Claycorp** [comment]
Can you upload what you have of 1.2.3 if its working? Removing the spam from a server of ~30 people would be great :P
