### ISSUE TITLE
Clean config files.

### ISSUE THREAD

**Issue by Claycorp** [UnderMybrella/TiM#4]
If you are going to have a directory you might as well just place all of your configs and other mod related info there.

Dump the old config system and place all the stuff in one directory. Tinkers Modifiers directory can contain both the JSON file and the Modifiers directory you have now. Makes things much simpler for people to use.

Also remove all the comments for the JSON file as it just makes things more complicated and confusing. This is best left for the wiki.

**Comment by UnderMybrella** [comment]
Originally the Modifiers directory was just going to be for the Modifiers, but you're probably right, just putting everything there would make life easier.
Next update (1.2.3) should fix that, the folder name has changed to reflect that too
